### ISSUE TITLE
Readme error in GRPC go examples

### ISSUE THREAD

**Issue by davix** [pact-foundation/pact-plugins#10]
In provider-go:
> pact_verifier_cli -f ../consumer-go/pacts/grpc-consumer-go-area-calculator-provider.json --transport grpc -p 39821

The json doesn't exist

In consumer-go:
> The test method [test_proto_client](https://github.com/pact-foundation/pact-plugins/blob/main/examples/gRPC/area_calculator/consumer-go/src/lib.rs) first sets

The link doesn't exist

**Comment by rholshausen** [comment]
The JSON file is created by running the consumer tests in consumer-go.
