### ISSUE TITLE
Pact Plugin CLI Fails on amazonlinux2: /lib64/libc.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by rmartine-ias** [pact-foundation/pact-plugins#11]
Steps to reproduce:
```bash
docker run --platform linux/amd64 -it amazonlinux:2.0.20221004.0

# From inside container:
yum install -y gzip
curl -L https://github.com/pact-foundation/pact-plugins/releases/download/pact-plugin-cli-v0.0.0/pact-plugin-cli-linux-x86_64.gz | gunzip --stdout > /usr/local/bin/pact-plugin-cli
chmod u+x /usr/local/bin/pact-plugin-cli
pact-plugin-cli --version
```

Output:
```bash
bash-4.2# pact-plugin-cli --version
pact-plugin-cli: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by pact-plugin-cli)
pact-plugin-cli: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by pact-plugin-cli)
```

Glibc version:
```bash
bash-4.2# ldd --version
ldd (GNU libc) 2.26
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by YOU54F** [comment]
Can you bump the version of glibc?

https://docs.pact.io/docker#requirements

> Pact currently requires glibc >= 2.29. Most modern debian-based images will ship with a compatible version

**Comment by rmartine-ias** [comment]
Unfortunately not, this is the base image our build system uses, and updating glibc could lead to unexpected behavior with other programs. When Amazon Linux 2022 (which has a later glibc version) is no longer in pre-release, we may migrate to that, but for now we're tied to Amazon Linux 2. (latest) It would be significant initial and ongoing work to support another image, or a nested image, due to how our system is designed.

Manual install of the plugins works fine, and they manage to run. If this is working as intended, you can close.

**Comment by rholshausen** [comment]
The latest version of pact-plugin-cli (0.0.3) is static compiled with musl and runs ok on amazonlinux
