### ISSUE TITLE
MockServerMismatchedRequests is not returning mismatches with grpc

### ISSUE THREAD

**Issue by opicaud** [pact-foundation/pact-plugins#12]
Hello,

When i am running the example with a dummy client like
`func GetRectangleAndSquareArea(address string) ([2]float32, error) {
	var a [2]float32
	a[0] = 12
	a[1] = 9
	return a, nil
}`

Consumer test are still green even if no interactions with the mock server has been done.
Is it an expected behaviour ?

Thanks 

Olivier

**Comment by YOU54F** [comment]
Hi, 

I think it’s a bug which was raised against the protobuf plug-in

https://github.com/pactflow/pact-protobuf-plugin/issues/15

I would expect a failure in that scenario and the result to be returned as true.

both Matt and I identified during our testing.

thanks for raising here.

also thanks for trying out the plug-in work!

**Comment by YOU54F** [comment]
Closing as I believe this is resolved, please feel free to raise a new issue if you or any other readers have problems
