### ISSUE TITLE
Is there a linux/arm64 binary?

### ISSUE THREAD

**Issue by noorul** [pact-foundation/pact-plugins#15]
I am looking for am64 Linux binary. I couldn't find one.

**Comment by rholshausen** [comment]
A linux/arm64 binary for what?

**Comment by noorul** [comment]
For pact-plugin-cli tool. I don't see Linux arm64 version at https://github.com/pact-foundation/pact-plugins/releases

**Comment by rholshausen** [comment]
Ah, let me add that for you

**Comment by noorul** [comment]
That will be great!

**Comment by rholshausen** [comment]
`0.0.4` released with ARM 64 binary
