### ISSUE TITLE
How can i resolve proto import 

### ISSUE THREAD

**Issue by dev-rgupta** [pact-foundation/pact-plugins#20]
My Main Proto file import other proto files so How can I resolve those import proto's?

I'm using java/kotlin and my Proto A -----import--> proto B-----import--->proto C and all protos are in diff package structure when I'm compiling Proto A, it's not able to resolve imports. I tried to take help from pact-plugin example but couldn't able to resolve complex or domain specific proto.

**Comment by rholshausen** [comment]
For the Protobuf plugin, you can provide additional directories to load proto files from, see https://github.com/pactflow/pact-protobuf-plugin#additionalincludes-string-or-liststring
