### ISSUE TITLE
Support descriptor_set_in to protoc

### ISSUE THREAD

**Issue by Yu-Xie** [pact-foundation/pact-plugins#30]
For passing down the protobuf files to protoc, it looks like we only take `-I` [here](https://github.com/pactflow/pact-protobuf-plugin/blob/9c075769a5b5d2d09c500b850930e6011a6b66ad/src/protoc.rs#L87), but not `--descriptor_set_in` so I assume it’s not supported today to take a self-inclusive descriptor set binary file instead of raw `.proto` files, if that’s the case is there a plan to support it?

**Comment by rholshausen** [comment]
This is actually an issue for the Protobuf plugin, so moving it there
