### ISSUE TITLE
Issue with matching a list of enums

### ISSUE THREAD

**Issue by Yu-Xie** [pact-foundation/pact-plugins#31]
In the matcher do we support list of enums?
```
  "request": {
    "states": [
      "matching(equalTo, 'ENUM_VAL_1')"
    ]
  },
```
I’m getting this error --- is it because enum is not added to [should_be_packed_type](https://github.com/pactflow/pact-protobuf-plugin/blob/9c075769a5b5d2d09c500b850930e6011a6b66ad/src/message_decoder/mod.rs#L334)?
```
Failed to match the request message - BodyMismatches({"$.states": [BodyMismatch { path: "$.states[0]", expected: Some(b"ENUM_VAL_1"), actual: Some(b"0102"), mismatch: "Expected and actual field have different types: 1:(states, Varint, Enum) = ENUM_VAL_1 and 1:(states, LengthDelimited, Unknown) = 0102" }]})
```

**Comment by rholshausen** [comment]
I think this is trying to incorrectly compare a single enum value with the list of repeated enum values.

**Comment by rholshausen** [comment]
Moved this to the Protobuf plugin project
