### ISSUE TITLE
Plugins within Junit4 consumers

### ISSUE THREAD

**Issue by rkrishnan2012** [pact-foundation/pact-plugins#34]
Hey folks, 
Is it possible to use the protobuf plugin with a Junit4 consumer? I see [an example](https://github.com/pact-foundation/pact-plugins/tree/main/examples/gRPC/area_calculator/consumer-jvm) with the calculator app using Junit5, but I don't see any examples of using a plugin in Pact with Junit4 to generate a contract.

Specifically, I am trying to generate a consumer contract within an Android project (which is limited to Junit4) and the docs for [pact-jvm-consumer-junit](https://docs.pact.io/implementation_guides/jvm/consumer/junit) doesn't indicate we can use plugins, and the source for `ConsumerPactBuilder` makes no reference to plugins.

**Comment by rholshausen** [comment]
JUnit 4 and 5 share the same DSL, so plugins should work with Junit 4 tests.
