### ISSUE TITLE
Filename `plugin.proto` is too generic, leading to conflict

### ISSUE THREAD

**Issue by ringods** [pact-foundation/pact-plugins#4]
I just bumped into this error, using `pact-go` together with the Go `pulumi` sdk, both registering `plugin.proto`:

```
panic: proto: file "plugin.proto" is already registered
        previously from: "github.com/pact-foundation/pact-go/v2/internal/native"
        currently from:  "github.com/pulumi/pulumi/sdk/v3/proto/go"
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```

Although both files have different `go_package` directives, as you can see here:

* https://github.com/pulumi/pulumi/blob/master/sdk/proto/plugin.proto
* https://github.com/pact-foundation/pact-plugins/blob/f0fdfefef0099518635329a6deab424961690b62/proto/plugin.proto

this doesn't seem to be enough. The filenames need to be unique as well, according this comment:

https://github.com/golang/protobuf/issues/1122#issuecomment-853158260

I’m from Pulumi and will submit a PR to change our filenames, but I strongly suggest to that you also rename your file to e.g. `pact-plugin.proto` or `pact/plugin.proto` to prevent future filename collisions. Since [protobuf-go v1.26](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.26.0), such a filename collision generates a `panic`.

**Comment by mefellows** [comment]
Thanks for reporting @ringods - I've just pushed out a fix to Pact Go now: https://github.com/pact-foundation/pact-go/commit/60aaec15bfb1eb361b0bc1e06cecee984bca0188.

**Comment by ringods** [comment]
Fixed at Pulumi side with https://github.com/pulumi/pulumi/pull/10074
