### ISSUE TITLE
plugin driver - switch to threads instead of tokio for loading plugins

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-plugins#68]
There is an issue affecting Pact-Go users, whereby using plugins will cause sporadic segmentation faults.

The root issue cause of the issue https://github.com/tokio-rs/tokio/issues/3520 - Signals do not add SA_ONSTACK which may cause linked Go applications to crash

We can switch to using std::process in rust, introduced in this [commit](https://github.com/pact-foundation/pact-plugins/commit/d9e441e967c7fb53dbe0992b2787dc21fbd67c7e#diff-5a5d79260a9aa82b30f9693013d16a88f6fc14135d71220b14655c64c7e8d4d5) for windows, which uses threads instead of tokio tasks

[threaded version](https://github.com/pact-foundation/pact-plugins/blob/main/drivers/rust/driver/src/child_process_windows.rs#L3)

[tokio version](https://github.com/pact-foundation/pact-plugins/blob/main/drivers/rust/driver/src/child_process.rs)

I've tested this out on my fork and it's resulting in stable ci runs for pact-go cross platform utilising the following pact plugins (avro, csv, protobuf, matt)

Note: Avro plugin has failed to load on windows since moving to threads in [commit](https://github.com/pact-foundation/pact-plugins/commit/d9e441e967c7fb53dbe0992b2787dc21fbd67c7e#diff-5a5d79260a9aa82b30f9693013d16a88f6fc14135d71220b14655c64c7e8d4d5) 

Amending the following logback.xml from the installed pact-avro-plugin

From

https://github.com/austek/pact-avro-plugin/blob/main/modules/plugin/src/main/resources/logback.xml

To

```xml
<configuration>
</configuration>
```

will allow the plugin framework to pick up the plugins loaded message (serverKey and port).

So there may be a change required in the pact-avro-plugin to support.

This can easily be reproduced with on a windows machine by performing `pact-plugin-cli install -y avro`

It would be nice to implement the plugin timeout for loading - todo [here](https://github.com/pact-foundation/pact-plugins/blob/c6dd2dd8f78d12961a840b9554241836f80ae4b5/drivers/rust/driver/src/child_process.rs#L93-L94) by an env var possibly (so its usable by ffi & cli users easily)

**Comment by rholshausen** [comment]
So where have we got with this? Do we still want to go ahead? Or should we wait until the startup issues are resolved?

**Comment by YOU54F** [comment]
still need to sort the plugin startup issue as that will propagate to macos/linux. the flush suggestion you mentioned, should hopefully resolve that. will check later today

then there is a sep issue about the plugin shutdown on windows for avro. but we aren’t any worse than today.

should we make it configurable so the user can choose to use tokio tasks or threads rather than just binning the tokio tasks off. i haven’t done any measurements to ascertain if either is slower

**Comment by YOU54F** [comment]
shutdown issue resolved with local testing, PR raised here, need to make a couple of changes

https://github.com/GuillaumeGomez/sysinfo/pull/1341

**Comment by YOU54F** [comment]
fixed the startup issues now, woohoo!

https://github.com/austek/pact-avro-plugin/pull/45/files

we lose the rolling file appender from the plugin for reasons unknown.

PR updated here https://github.com/pact-foundation/pact-plugins/pull/69

**Comment by YOU54F** [comment]
pact-avro-plugin pr merged and released as 0.0.6 which gets us starting up 

https://github.com/pact-foundation/pact-go/actions/runs/10637661001/job/29491970199

need #69 merging which will fix #73
