### ISSUE TITLE
New JVM release that will allow migration to 4.x Protobuf?

### ISSUE THREAD

**Issue by eroznik** [pact-foundation/pact-plugins#72]
Hey,

Given that the JAR of the Plugin Core includes compiled Proto classes, it would be great to have a release which would have the classes compiled with protoc of at least version 3.22.0 ( [ref](https://github.com/protocolbuffers/protobuf/issues/16452#issuecomment-2134644103) ).

Based on [this](https://github.com/pact-foundation/pact-plugins/commit/5a8e1df161fe7707146ea06b31588b35e9af2d08) commit, the work has already been done, so we might just be waiting on a new release?

Best regards,
E.

**Comment by rholshausen** [comment]
0.5.0 JVM release is done
