### ISSUE TITLE
Verifying provider's plugin pacts hang on Windows

### ISSUE THREAD

**Issue by tienvx** [pact-foundation/pact-plugins#8]
When I verify provider's pacts that required plugins (csv, protobuf), on Linux and Mac, it work fine, but on Windows it hang.

As you can see here https://github.com/tienvx/pact-php/actions/runs/3099040342 , all tests **passed** on Linux and Mac. On Windows it **hang** for hours. I have to cancel it manually.

This is how it look like on a Windows machine:
![task-manager](https://user-images.githubusercontent.com/3327643/191640597-c5f6a24e-861e-4ffb-a04c-c98d24e95e9d.png)

Some information to help debugging:
* To reproduce yourself: `composer test` or `vendor/bin/phpunit --debug -c example/phpunit.provider.xml`
* Consumer tests that require plugins (csv, protobuf) does not affect by this bug. I run `vendor/bin/phpunit --debug -c example/phpunit.plugins.xml` and it passed
* It happen on calling this ffi method `pactffi_verifier_execute` https://github.com/tienvx/pact-php/blob/rust-ffi-plugins-downloads/src/PhpPact/Standalone/ProviderVerifier/Verifier.php#L163
* Version:
  * pact-ffi: 0.3.11
  * pact-csv-plugin: 0.0.3
  * pact-protobuf-plugin: 0.1.13
* Pacts: https://github.com/tienvx/pact-php/tree/rust-ffi-plugins-downloads/example/pacts
* The contents of pact files seems doesn't matter, because:
  * Although they are generated by old version of plugins (`0.0.0` for csv, `0.0.2` for protobuf), the tests are passed, for Linux, Mac, Windows (but hang after that, see image above).
  * If I replace them by pacts generated by latest version of plugins (see above), it will still hang

**Comment by rholshausen** [comment]
I've had the same issue with the pact-plugin-cli. In that case, it looked like the HTTP reqwest client was holding a connection open and the Tokio runtime was not shutting down.

**Comment by tienvx** [comment]
Look like this bug has been fixed to me:
- pact-ffi: 0.4.4
- pact-csv-plugin: 0.0.3
- pact-protobuf-plugin: 0.3.0
- OS: Windows Server 2022 (`windows-latest` from Github Actions)

**Comment by rholshausen** [comment]
I haven't done anything. Hopefully it was a dependency update that fixed the issue.

**Comment by YOU54F** [comment]
Thanks for recoding the versions @tienvx we could probably replicate the scenario where it hung and upgrade dependencies until we track down which one makes it break, if we fancy a trip down dependency lane.
